### ISSUE TITLE
Limit the number of yarn used

### ISSUE THREAD

**Issue by copperwall** [copperwall/Cat-Defense#2]
There should be an indicator of how much yarn a person can use. The mechanic could be something like there can only be three pieces of yarn in play at anytime. If a yarn is destroyed it comes back into play, so we reward players for using yarn in good ways.

Playing a piece of yarn in an inopportune place means you might not get it back. This can work similarly to how we limit the number of cats in play and then recycle the sprite when they "die".

**Comment by copperwall** [comment]
This works but could use a UI thing

**Comment by addison-grant** [comment]
There is a UI element in the upper-left corner indicating the number of yarn in your inventory.
